### ISSUE TITLE
Blog Layout and Style Improvement

### ISSUE THREAD

**Issue by Codipk** [ContriHUB/CREDLOCKS#1]
🐛Bug-Report

### Expected behavior
The blog post layout should be visually appealing and easy to navigate. The image size should be proportionate to the content, and the placement of elements such as the title, author name, date, and social sharing buttons should follow a logical hierarchy. There should be enough spacing between the description and other elements to ensure readability.

### Current behavior
The current blog layout is cluttered, and the image is too large, dominating the content area. The placement of the title, metadata (author name, date), and social sharing buttons is not intuitive. Additionally, the blog description is positioned too close to other elements, causing readability issues.
<img width="1198" alt="Screenshot 2024-10-04 at 12 42 18 PM" src="https://github.com/user-attachments/assets/ac6584ff-5e64-424a-96e4-0e0ddc8a4b82">

### Steps to reproduce

1.Open the blog post.
2.Observe the size of the image compared to the text content.
3.Note the placement of the title, author name, date, and social sharing buttons.
4.Review the spacing between the description and other elements.

### Possible Solution
Resize the image to fit more appropriately within the content area.
Reposition the title, metadata, and social sharing buttons to create a clear visual hierarchy.
Adjust the spacing between the description and other elements to enhance readability.
Improve the UI by adding a background or incorporating other design elements to make the blog layout more visually appealing.

### Context (Your working environment)
Browser: Chrome

**Comment by Ayush5071** [comment]
@Codipk can you please assign this issue to me,i have already worked on Blog applications.

**Comment by Codipk** [comment]
@Ayush5071 You can start working on this issue after your work will be done you have to attach valid video or screenshot of UI working.

**Comment by Harishnandre** [comment]
Could you please assign this issue to me, I have worked on this type of Issues.

**Comment by Harishnandre** [comment]
@Codipk Could you please assign this issue, I have already worked on this type of issues.

**Comment by Ayush5071** [comment]
@Codipk I'm having issue with creating a blog post, not able to select any category and it is reqquired field sowithout it form cannot be submitted, so how would i work
![Uploading Screenshot 2024-10-09 143323.png…]()

**Comment by Codipk** [comment]
You have to make schema first in mongo db compass  and there in category schema u have to do entry manually in db.

<img width="853" alt="Screenshot 2024-10-09 at 3 37 46 PM" src="https://github.com/user-attachments/assets/7d9fb40a-3f29-4ff6-b3bb-ffa0eafb3d60">

@Ayush5071  can u attach ss?

**Comment by Ayush5071** [comment]
okay sir,I understood ,Thanks.

**Comment by Ayush5071** [comment]
https://github.com/user-attachments/assets/3f23ea87-f1ba-4b9c-872e-8f2ae969bf77

@Codipik , sir i have improved the UI of Individual Blog, see if you want to improve anything specifically more please inform me.

**Comment by Codipk** [comment]
OK  @Ayush5071 , You can make a PR request for verification

**Comment by Ayush5071** [comment]
@Codipk Ma'am,I raised the pull request also added the link in contrihub website.
Also, Please, let me know if i have to work on more issue in this Codebase, like we shoul assign categories at start so,it would avoid hardcode the data in database.

**Comment by Codipk** [comment]
Okay , I have merged ur Pr
