### ISSUE TITLE
Enhance the UI for "Add-Case" and "Settings (Edit Profile)" sections.

### ISSUE THREAD

**Issue by Codipk** [ContriHUB/CREDLOCKS#11]
The current UI of the "Add-Case" and "Settings (Edit Profile)" sections is missing certain visual elements such as borders, outlines, and proper alignment. Improving these aspects will enhance the overall user experience and ensure a consistent, polished look throughout the platform.

# CURRENT UI Of EDIT PROFILE (SETTINGS):
<img width="943" alt="Screenshot 2024-10-17 at 12 14 11 PM" src="https://github.com/user-attachments/assets/dd7c54be-dc4b-4c7a-97db-9e5dce807c3e">

#  CURRENT UI Of Add-Case PROFILE :
<img width="1392" alt="Screenshot 2024-10-17 at 12 21 27 PM" src="https://github.com/user-attachments/assets/91370d81-efdb-47cc-bd8f-ef39eee47e15">

 # Solution:
1. Borders and Outlines: Add appropriate borders and outlines to input fields, buttons, and form sections where necessary.
2. Alignment: Ensure all elements, including input fields, buttons, and labels, are properly aligned for a clean, organized layout.
3. Spacing: Improve the padding and margins to create more space between form elements for better readability.
4. Button Styling: Ensure that the buttons (e.g., "Submit", "Save Changes") are clearly distinguishable, with hover effects and proper alignment relative to the form field.

Bonus Points: Special consideration will be given based on the visual appeal of the redesigned UI, making aesthetics a critical factor.

**Comment by Vaishnavi1047** [comment]
@Codipk i have sent the req for this issue

**Comment by Codipk** [comment]
As per rules first come first serve @Ayush5071 assign this issue. Strt working and do comment here also

**Comment by Ayush5071** [comment]
I'm working on this issue

**Comment by Ayush5071** [comment]
@Codipk  ma'am i raised the pull request.

**Comment by Codipk** [comment]
@Ayush5071 Since u have time so can u fix the bug which is on editing the profile details while saving error is coming.Resolve this

**Comment by Ayush5071** [comment]
Sure, mam i think there is error in target url of server, the edit request is not able to go to their route I'll try to fix it, but i think it will take time.

**Comment by Codipk** [comment]
@Ayush5071 np, u can request for approval otherwise if u have time then do it.

**Comment by Ayush5071** [comment]
Okay ma'am I'll try to do it by tonight

**Comment by Codipk** [comment]
@Ayush5071 wht the updates?If u are not able to do solve the bug then make the request for approval

**Comment by Ayush5071** [comment]
@Codipk i'm really sorry mam , i got busy bcz of smp and tpo meets.
also,not able to solve the error in traget url . i have sended the approval of this issue.
