### ISSUE TITLE
 Add Password Visibility Toggle on Signup and Login Pages

### ISSUE THREAD

**Issue by Codipk** [ContriHUB/CREDLOCKS#2]
### Problem
Currently, users are unable to see the password they are typing on the signup and login pages. This can lead to frustration due to mistyping or having to re-enter passwords multiple times.

### Proposed Solution
Add a "password visibility toggle" feature on both the signup and login forms. This toggle button would allow users to switch between showing or hiding their password input. Typically, this is represented by an "eye" icon next to the password field.

When clicked, the password should be visible.
Clicking it again should hide the password.
The toggle should:
Use an eye icon for visual indication.
Default to a hidden state (password should be masked initially).

Let me know if any more information is needed for this feature.
Here in the password field add a toggle button
<img width="1205" alt="Screenshot 2024-10-05 at 11 16 12 PM" src="https://github.com/user-attachments/assets/c82fc91c-faa2-4239-b9ef-8535af8ddab9">

**Comment by manu-hn** [comment]
Hi, @Codipk 

I’ve raised a PR for the password toggle feature—please review it when you get a chance. I also noticed a lack of responsiveness in the app. If you’d like, feel free to raise an issue with the appropriate labels, or let me know if I should raise it myself.

I'm really happy to contribute and help your project grow!

**Comment by lakshitrajput** [comment]
Can you assign me this issue ?
I have fixed it.

**Comment by Codipk** [comment]
According to the rules @lakshitrajput, please start working on this issue. After you complete the task, create a pull request (PR) and make sure to attach a screenshot of your work on the website to showcase what you've done.

**Comment by Codipk** [comment]
> Hi, @Codipk
> 
> I’ve raised a PR for the password toggle feature—please review it when you get a chance. I also noticed a lack of responsiveness in the app. If you’d like, feel free to raise an issue with the appropriate labels, or let me know if I should raise it myself.
> 
> I'm really happy to contribute and help your project grow!

For solving the issue you have to send the request from Contrihub website only
