### ISSUE TITLE
Add Favicon to the Website

### ISSUE THREAD

**Issue by Codipk** [ContriHUB/CREDLOCKS#3]
### Problem
The website currently does not have a favicon. Favicons are important for brand recognition and improve the user experience by making it easier to identify the website in browser tabs, bookmarks, and history.

### Proposed Solution
Add a favicon to the website, ensuring it displays in the browser tab when users visit any page.

### Create a favicon in .ico or .png format.
Link it in the head section of the website’s HTML:

Ensure the favicon represents the website's branding and is of appropriate size (typically 16x16, 32x32, or 48x48 pixels) also same as of logo

Make sure to replace this react favicon with the one which match with the logo and place that file in the same place as shown in this figure
<img width="345" alt="Screenshot 2024-10-05 at 11 30 42 PM" src="https://github.com/user-attachments/assets/733a2fc0-2a03-4ae4-8130-589eee36ba8f">

**Comment by VishalMinj** [comment]
I'd like to contribute. Please assign me this task

**Comment by Codipk** [comment]
@VishalMinj , please start working on this issue. After you complete the task, create a pull request (PR) and make sure to attach a screenshot of your work on the website to showcase what you've done.

**Comment by VishalMinj** [comment]
![image](https://github.com/user-attachments/assets/beacf150-159b-4a70-8d1e-bfd862dc3297)
Not sure if this looks decent. Please verify @Codipk

**Comment by Codipk** [comment]
Try some rounded shape that will look decent use logo maker or use canva Or just remove the text of Credlock from the favicon then try. It's upto you

**Comment by VishalMinj** [comment]
![image](https://github.com/user-attachments/assets/00c1f950-d1ac-4a44-81c3-6d29a251f45f)
This one looks fine and also goes well along with the navbar logo @Codipk

**Comment by Codipk** [comment]
Yes
