### ISSUE TITLE
Remove the Follow Button from My_Profile

### ISSUE THREAD

**Issue by Codipk** [ContriHUB/CREDLOCKS#8]
# The "Follow" button is showing on the user's own profile and needs to be removed or hidden.
The "Follow" button appears on the user's own profile and needs to be removed.

### Expected Behavior
The "Follow" button should be removed from the user's own profile page, as it serves no purpose. The rest of the profile page should remain functional, without affecting the "Follow" button visibility on other users' profiles.

### Current Behavior
The "Follow" button is currently visible on the user's own profile page, which is unnecessary. This button should only be available when viewing other users' profiles, such as when clicking on an author's username from a blog post.

### Steps to Reproduce
Log into the CredLock Homes platform.
Navigate to the "My Profile" section.
Observe the "Follow" button on the user's own profile page.
Click on a different user's username from a blog post to view their profile.
The "Follow" button appears correctly on another user's profile.
### Possible Solution
Remove the "Follow" button from the user's own profile page, ensuring that other functionality on the page is unaffected.
Ensure that the "Follow" button remains visible when viewing another user's profile, such as when clicking on a blog post author's name.
<img width="858" alt="Screenshot 2024-10-17 at 8 21 16 AM" src="https://github.com/user-attachments/assets/2fd09439-cecb-4927-bf65-7821213be5c1">

**Comment by Codipk** [comment]
@RajatX24 You can start working!!

**Comment by RajatX24** [comment]
Thank you for assigning. Working on it now.

**Comment by RajatX24** [comment]
hello @Codipk ,

I have created a PR for this issue, you can check it out here: https://github.com/ContriHUB/CREDLOCKS/pull/12
If there are changes that need to be made please let me know.

Thanks

**Comment by Codipk** [comment]
@RajatX24 U can now raise the request for PR I have reviewed ur code it's fine
