### ISSUE TITLE
Improve the UI for MY_Profile section

### ISSUE THREAD

**Issue by Codipk** [ContriHUB/CREDLOCKS#9]
## Current 
Ui for MY Profile does not look engaging.
<img width="862" alt="Screenshot 2024-10-17 at 8 20 28 AM" src="https://github.com/user-attachments/assets/07bf0201-c279-4f31-8071-12718db372ea">

## Expected
1. Make the Ui somewhat like this ensuring that all functionalities should be in working mode.
![image](https://github.com/user-attachments/assets/00746cc0-4d0b-4738-a0f5-2b8a481edc5f)

2. For the about section go to settings enter your details update ur profile then if the person has written about section then display about him also in My profile page.

NOTE-Below the User details all his blogs should be visible in card format.

**Comment by devagn611** [comment]
Assign me this issue

**Comment by Codipk** [comment]
@divyanshu-912 Strt working on this issue. Also comment here so that I make u assignee

**Comment by VishalMinj** [comment]
If this issue is vacant then please assign me with it, I've already sent the request

**Comment by Codipk** [comment]
@VishalMinj before ur request he had requested so acc to the rule FCFS he got, if he unable to submit the Pr, then I'lll assign u

**Comment by divyanshu-912** [comment]
> @divyanshu-912 Strt working on this issue. Also comment here so that I make u assignee

I am working on it

**Comment by VishalMinj** [comment]
@Codipk is this issue open now?

**Comment by ShivaniSaini123** [comment]
@Codipk Has this issue been resolved or not? Please assign it to me

**Comment by divyanshu-912** [comment]
Sorry, I am unable to complete it , you can assign it to any other

**Comment by Codipk** [comment]
@VishalMinj u r assigned to this isssue.Strt working on it

**Comment by VishalMinj** [comment]
Okay @Codipk

**Comment by VishalMinj** [comment]
It's not letting me login

![image](https://github.com/user-attachments/assets/1f2d18c2-47e4-4ee0-a185-5ead71eb4543)
![image](https://github.com/user-attachments/assets/6e5ae430-e5d6-4770-934a-fc34b326589a)

**Comment by Codipk** [comment]
Have u sign up?

**Comment by VishalMinj** [comment]
By this, did you meant  a env var
![image](https://github.com/user-attachments/assets/69b1a086-7798-4391-a607-4e8c1ee5edc6)

**Comment by VishalMinj** [comment]
> Have u sign up?

Yeah I had to make a bypass to signup
cause even that was not working

**Comment by Codipk** [comment]
> By this, did you meant a env var ![image](https://private-user-images.githubusercontent.com/119677246/378512415-69b1a086-7798-4391-a607-4e8c1ee5edc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1Mjc3MDQsIm5iZiI6MTcyOTUyNzQwNCwicGF0aCI6Ii8xMTk2NzcyNDYvMzc4NTEyNDE1LTY5YjFhMDg2LTc3OTgtNDM5MS1hNjA3LTRlOGMxZWU1ZWRjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQxNjE2NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOWI5YjdlNWNiYmVjYjU0YTQ4ZDhmNzg0ZGZkYzA1OGRlNDE0NzEwY2RlMjRiZDllYzVmNzhjOTlhYjlhNTA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.g2xfNI-F8WAtWqT0xtABYoTTKm4aEKnUvRLpS2eqhrM)

Yes

**Comment by VishalMinj** [comment]
Added the jwt in env .
still, the login is not working

**Comment by Codipk** [comment]
Dm on discord -diptikumari0337

**Comment by VishalMinj** [comment]
I Just noticed 
![image](https://github.com/user-attachments/assets/d4f3dc78-8108-4b45-a3e3-5cea0c1e988a)
did you set the api endpoint with 4000 or 8000?

**Comment by Codipk** [comment]
@VishalMinj just chk whatever is the available ports assigned that one .

**Comment by Codipk** [comment]
do it 4000

**Comment by VishalMinj** [comment]
NOT mentioned in README 
![image](https://github.com/user-attachments/assets/b675e5f7-b797-48f4-834f-e427591340b2)

**Comment by Codipk** [comment]
@VishalMinj Come to discord

**Comment by VishalMinj** [comment]
hey @Codipk, Here's the preview. Thought of a few more things but that might break the original responsive code. Provide feedback if any changes needed

![image](https://github.com/user-attachments/assets/9f6ce58d-c3a4-43d2-9f92-c08375af6eaf)
![image](https://github.com/user-attachments/assets/5e327889-de88-4579-9067-5a031c9a38fd)

**Comment by Codipk** [comment]
@VishalMinj there is one more thing when u click on others user's blog then click on their username then follow button will be appear so chk that also bcoz u have improve the a logged in person profile . 
<img width="798" alt="Screenshot 2024-10-22 at 8 51 13 AM" src="https://github.com/user-attachments/assets/04d65ce4-c692-468a-a41f-b547b8936b60">
Here is the follow button adjust it's style layout also

**Comment by VishalMinj** [comment]
Done @Codipk 
![image](https://github.com/user-attachments/assets/bf67bf15-183e-4202-9310-42f090eeef48)

Anything else to toggle in ui or can I start figuring the db?

**Comment by Codipk** [comment]
No, it's fine now

**Comment by Codipk** [comment]
If everything is done u can create a pr
